package net.game.aura;

public enum AuraEffect {

	REDUCE_STAMINA,
	REDUCE_MAX_STAMINA,
	REDUCE_MANA,
	REDUCE_MAX_MANA,
	REDUCE_ARMOR,
	REDUCE_CARAC,
	REDUCE_STRENGTH,
	REDUCE_AGILITY,
	REDUCE_ATTACK_POWER,
	REDUCE_INTELLIGENCE,
	REDUCE_SPELL_POWER,
	REDUCE_ATTACK_SPEED,
	UP_STAMINA,
	UP_MAX_STAMINA,
	UP_STRENGTH,
	UP_AGILITY,
	UP_MANA,
	UP_MAX_MANA,
	MOUNT,
	;
}
